// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY1fk0HJsICjNoxMbPIXFby_d0EPn1q48',
    appId: '1:416753957761:web:54afcd572dfc947b0c4680',
    messagingSenderId: '416753957761',
    projectId: 'emergencymate-dc1ca',
    authDomain: 'emergencymate-dc1ca.firebaseapp.com',
    storageBucket: 'emergencymate-dc1ca.appspot.com',
    measurementId: 'G-4BT1BYXB2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-nFXK22Nsp_6QiO6W_uYzg05n3wz9QTU',
    appId: '1:416753957761:android:9de07266a82277aa0c4680',
    messagingSenderId: '416753957761',
    projectId: 'emergencymate-dc1ca',
    storageBucket: 'emergencymate-dc1ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPa6zXDVyuCweTKCjaPCmS03jABtA2k8k',
    appId: '1:416753957761:ios:dfeb85955b111c2d0c4680',
    messagingSenderId: '416753957761',
    projectId: 'emergencymate-dc1ca',
    storageBucket: 'emergencymate-dc1ca.appspot.com',
    iosClientId: '416753957761-94rvcj3ncuf8ho8g821uflebackrmq77.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPa6zXDVyuCweTKCjaPCmS03jABtA2k8k',
    appId: '1:416753957761:ios:9d981a88b7ba57610c4680',
    messagingSenderId: '416753957761',
    projectId: 'emergencymate-dc1ca',
    storageBucket: 'emergencymate-dc1ca.appspot.com',
    iosClientId: '416753957761-m5dqa4jhesprmep00uqhgn23j08p427d.apps.googleusercontent.com',
    iosBundleId: 'com.example.emergencyMate.RunnerTests',
  );
}
